language: php
php:
  - '7.0'
  - hhvm
  - nightly

matrix:
    allow_failures:
        - php:
            - hhvm
            - nightly

before_script:
  - composer install && composer dump-autoload -o

script: ./vendor/bin/phpunit